import { Link } from "react-router-dom";

const FractalsPage: React.FC = () => {
    return (
        <>
            <div className="container mx-auto px-4 py-8">
                <h1 className="text-3xl font-bold text-blue-700 mb-6">Fractals Visualization</h1>
                
                <p className="text-lg mb-4">
                    Explore the fascinating world of mathematical fractals - geometric figures with patterns 
                    that repeat infinitely at different scales. These self-similar structures appear throughout 
                    nature and have applications in mathematics, computer science, and art.
                </p>
                <p className="text-lg mb-8 text-blue-600 italic">
                    <strong>Note:</strong> Unlike sorting and pathfinding, fractals are not algorithms themselves but rather mathematical objects or patterns. 
                    However, they are typically generated using algorithms, often recursive ones, making them an interesting complement to algorithmic visualizations.
                </p>
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
                    <div className="bg-white rounded-lg shadow-md overflow-hidden transition-all duration-300 hover:shadow-xl hover:-translate-y-1 flex flex-col">
                        <div className="h-52 relative overflow-hidden flex items-center justify-center">
                            <img
                                src="fractal-imgs/pythagoras-tree.PNG"
                                alt="Pythagoras Tree"
                                className="max-w-full max-h-full object-contain"
                            />
                        </div>
                        <div className="p-6 flex flex-col flex-1">
                            <h2 className="text-xl font-semibold text-blue-700 mb-2">Pythagoras Tree</h2>
                            <p className="text-gray-600 mb-4 flex-1">
                                The Pythagoras Tree is a geometric fractal built from squares. Starting with an initial square,
                                two smaller squares are positioned on one of its sides, creating a structure resembling a tree.
                            </p>
                            <Link
                                to="/fractals/pythagoras-tree"
                                className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md transition-colors duration-200 shadow-sm hover:shadow self-start"
                            >
                                Explore Visualization
                            </Link>
                        </div>
                    </div>
                    <div className="bg-white rounded-lg shadow-md overflow-hidden transition-all duration-300 hover:shadow-xl hover:-translate-y-1 flex flex-col">
                        <div className="h-52 relative overflow-hidden">
                            <img
                                src="fractal-imgs/mandelbrot.jpg"
                                className="w-full h-full object-cover"
                            />
                        </div>
                        <div className="p-6 flex flex-col flex-1">
                            <h2 className="text-xl font-semibold text-gray-500 mb-2">Mandelbrot set</h2>
                            <p className="text-gray-600 mb-4 flex-1">
                                The Mandelbrot Set is a famous fractal generated by a simple mathematical equation. When plotted,
                                it creates intricate, infinitely complex patterns. Zooming reveals endless detail and mini replicas of the entire set
                            </p>
                            <button
                                className="bg-gray-400 text-white font-bold py-2 px-4 rounded-md cursor-not-allowed opacity-70 self-start"
                                disabled
                            >
                                Coming Soon
                            </button>
                        </div>
                    </div>
                </div>
                
                <div className="bg-gradient-to-br from-gray-50 to-gray-100 p-6 rounded-lg shadow-md mb-8 border border-gray-200">
                    <h2 className="text-2xl font-bold text-blue-700 mb-4">What are Fractals?</h2>
                    <p className="text-gray-700 mb-4 leading-relaxed">
                        Fractals are infinitely complex patterns that are self-similar across different scales.
                        They are created by repeating a simple process over and over in an ongoing feedback loop.
                        Driven by recursion, fractals are images of dynamic systems – the pictures of Chaos.
                    </p>
                    <p className="text-gray-700 leading-relaxed">
                        Geometrically, they exist in between our familiar dimensions. Fractal patterns are extremely 
                        familiar, since nature is full of fractals. For instance: trees, ferns, clouds, snowflakes, 
                        mountains, lightning bolts, and even our own circulatory systems.
                    </p>
                </div>
                
                <div className="bg-gradient-to-br from-blue-50 to-blue-100 p-6 rounded-lg shadow-md mb-8 border border-blue-200">
                    <h2 className="text-2xl font-bold text-blue-700 mb-4">Fractals in Mathematics and Computing</h2>
                    <p className="text-gray-700 mb-4 leading-relaxed">
                        In computing, fractals have revolutionized image compression technology and computer graphics.
                        They've also helped describe the behavior of chaotic systems like weather patterns and stock market fluctuations.
                    </p>
                    <p className="text-gray-700 leading-relaxed">
                        The algorithms behind fractals often involve simple mathematical formulas repeated in feedback loops,
                        demonstrating how complexity can emerge from simplicity through iteration.
                    </p>
                </div>
            </div>
        </>
    );
};

export default FractalsPage;